### ISSUE TITLE
Holidays breaks on HA 2022.3.0+

### ISSUE THREAD

**Issue by cerebrate** [bruxy70/Holidays#29]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Steps to reproduce:

Upgrade a working installation with Holidays to 2022.3.0 or above

holidays.calendar sensor is unavailable

The following error appears repeatedly in the system log:

```
2022-03-04 19:29:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.holidays fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_device_update
raise exc
File "/config/custom_components/holidays/calendar.py", line 243, in async_update
await self._async_load_holidays()
File "/config/custom_components/holidays/calendar.py", line 75, in _async_load_holidays
hol = create_holidays(
File "/config/custom_components/holidays/__init__.py", line 137, in create_holidays
return holidays.country_holidays(country, **kwargs)
AttributeError: module 'holidays' has no attribute 'country_holidays'
```

### Configuration

```JSON
{
  "home_assistant": {
    "installation_type": "Unknown",
    "version": "2022.3.1",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": false,
    "arch": "x86_64",
    "timezone": "America/Chicago",
    "os_name": "Linux",
    "os_version": "4.19.0-18-amd64",
    "run_as_root": true
  },
  "custom_components": {
    "nodered": {
      "version": "1.0.6",
      "requirements": []
    },
    "hacs": {
      "version": "1.23.0",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "magic_areas": {
      "version": "3.0.0-beta",
      "requirements": []
    },
    "pyscript": {
      "version": "1.3.2",
      "requirements": [
        "croniter==1.0.2",
        "watchdog==2.0.3"
      ]
    },
    "alexa_media": {
      "version": "3.10.15",
      "requirements": [
        "alexapy==1.25.3",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "icloud3": {
      "version": "2.4.6",
      "requirements": []
    },
    "adaptive_lighting": {
      "version": "1.0.14",
      "requirements": []
    },
    "grocy": {
      "version": "v3.0.1",
      "requirements": [
        "pygrocy==1.0.0",
        "iso8601==0.1.12",
        "integrationhelper==0.2.2"
      ]
    },
    "browser_mod": {
      "version": "1.3.1",
      "requirements": []
    },
    "plex_recently_added": {
      "version": "0.3.8",
      "requirements": []
    },
    "garbage_collection": {
      "version": "4.6",
      "requirements": [
        "python-dateutil>=2.8.2"
      ]
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "var": {
      "version": "0.12.3",
      "requirements": []
    },
    "notify_mqtt": {
      "version": "0.1.1",
      "requirements": []
    },
    "anniversaries": {
      "version": "4.5.0",
      "requirements": [
        "python-dateutil>=2.8.1",
        "integrationhelper>=0.2.2",
        "voluptuous>=0.12.1"
      ]
    },
    "attributes": {
      "version": "1.2.0",
      "requirements": []
    },
    "saver": {
      "version": "v1.1.3",
      "requirements": []
    },
    "weatheralerts": {
      "version": "0.1.5",
      "requirements": []
    },
    "pid_controller": {
      "version": "v1.1.3",
      "requirements": []
    },
    "blitzortung": {
      "version": "1.0.1",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "calendarific": {
      "version": "0.14.0",
      "requirements": [
        "sampleclient",
        "integrationhelper"
      ]
    },
    "car_wash": {
      "version": "1.5.2",
      "requirements": []
    },
    "spotcast": {
      "version": "v3.6.27",
      "requirements": [
        "spotify_token==1.0.0"
      ]
    },
    "authenticated": {
      "version": "21.9.0",
      "requirements": []
    },
    "holidays": {
      "version": "1.7.1",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.13"
      ]
    },
    "o365": {
      "version": "v2.3.1",
      "requirements": [
        "O365==2.0.18.1",
        "BeautifulSoup4>=4.10.0"
      ]
    },
    "cryptoinfo": {
      "version": "0.0.10",
      "requirements": []
    },
    "readme": {
      "version": "0.4.0",
      "requirements": []
    },
    "config_check": {
      "version": "0.1.1",
      "requirements": []
    },
    "powercalc": {
      "version": "v0.18.4",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "schedule_state": {
      "version": "0.12.2",
      "requirements": [
        "portion==2.2.0"
      ]
    },
    "thermal_comfort": {
      "version": "1.4.3",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "holidays",
    "name": "Holidays",
    "version": "1.7.1",
    "documentation": "https://github.com/bruxy70/Holidays/",
    "issue_tracker": "https://github.com/bruxy70/Holidays/issues",
    "iot_class": "calculated",
    "dependencies": [],
    "config_flow": true,
    "codeowners": [
      "@bruxy70"
    ],
    "requirements": [
      "python-dateutil>=2.8.2",
      "holidays>=0.13"
    ],
    "is_built_in": false
  },
  "data": {
    "entity_id": "calendar.holidays",
    "state": null,
    "attributes": {
      "next_date": null,
      "next_holiday": null,
      "last_updated": null,
      "holidays": {}
    },
    "config_entry": {
      "entry_id": "79fbd98da7963089e2d3743686067c21",
      "version": 2,
      "domain": "holidays",
      "title": "Holidays",
      "data": {
        "unique_id": "41ab6991-7b97-48d7-9ad5-7d2e0edfdb5c",
        "icon_normal": "mdi:trash-can",
        "icon_today": "mdi:delete-restore",
        "icon_tomorrow": "mdi:delete-circle",
        "country": "US",
        "observed": true,
        "subdiv": "KS"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    }
  }
}
```

### Debug logs

```shell
2022-03-04 19:29:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.holidays fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_device_update
raise exc
File "/config/custom_components/holidays/calendar.py", line 243, in async_update
await self._async_load_holidays()
File "/config/custom_components/holidays/calendar.py", line 75, in _async_load_holidays
hol = create_holidays(
File "/config/custom_components/holidays/__init__.py", line 137, in create_holidays
return holidays.country_holidays(country, **kwargs)
AttributeError: module 'holidays' has no attribute 'country_holidays'
```

**Comment by bruxy70** [comment]
Not sure what is your installation type. But you need to have holidays library version 0.13. This normally comes with HA 2022.3.x (with teh workday integration) . Looks like not on your system for some reason. Do you perhapos have a custom version of workday?

**Comment by cerebrate** [comment]
It's containerized; it shows as unknown, I think, because I'm running it in k3s rather than docker.

No custom version of workday, but curiously enough, I've had an issue with workday as well after this upgrade, so given your comment I took a look under _deps_ and found that for some reason there was an old version of the holidays library (0.12) installed in there, presumably from a previous install of this (not sure I have anything else that uses it)? Deleting that seems to have fixed both this issue and the one with workday.
