### ISSUE TITLE
Subdivision holiday missing from ignore list

### ISSUE THREAD

**Issue by amdbuilder** [bruxy70/Holidays#44]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

When configuring a helper (Country: US Subdivision: NC) not all of the populated holidays are available to ignore.

I was able to confirm the issue is specific to the subdivision by configuring a second instance without subdivision (blue).  The first instance with subdivision adds a "Day After Christmas" holiday.
![image](https://user-images.githubusercontent.com/437374/209586405-e1b1a9e1-f9d8-407c-a6e1-0d672335c1a9.png)

This holiday isn't available to exclude when checking the helper settings:
![image](https://user-images.githubusercontent.com/437374/209586389-3d769194-24fd-4832-a33f-9f6b3189637b.png)

### Configuration

```JSON
Unable to download diagnostic as something "when wrong" when attempting.  

Home Assistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - lates

Holidays version 1.9.2 (just installed)
```

### Debug logs

```shell
Error is likely related to attempts to download diagnostic data instead of the reported issue.

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/holidays/diagnostics.py:21
Integration: Holidays (documentation, issues)
First occurred: 5:35:58 PM (12 occurrences)
Last logged: 5:39:13 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 211, in get
    data = await info[d_type.value](hass, config_entry)
  File "/config/custom_components/holidays/diagnostics.py", line 18, in async_get_config_entry_diagnostics
    entity_data = [
  File "/config/custom_components/holidays/diagnostics.py", line 21, in <listcomp>
    if entities[entity].unique_id == entry.data["unique_id"]
KeyError: 'unique_id'
```

**Comment by bruxy70** [comment]
I think it was because it overlaps with the observed Christmas Day. The holidays normally show up twice for the observed holidays, and I ignore the ones that are observed, otherwise they will be twice.
Anyhow, trying something else - compiling the pop list with observed set to false. Hopefully that will work.

**Comment by amdbuilder** [comment]
The latest update resolves the problem.  Thank you for the quick fix!
