### ISSUE TITLE
AttributeError: 'Holidays' object has no attribute '_language'

### ISSUE THREAD

**Issue by vlad36N** [bruxy70/Holidays#56]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Hi. After update to latest version 1.9.7 Holidays has error and not loaded

### Configuration

```JSON
Before update has been loaded.
```

### Debug logs

```shell
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:696
First occurred: 6:46:38 AM (35 occurrences)
Last logged: 6:52:18 AM

Update for calendar.holidays_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/holidays/calendar.py", line 274, in async_update
    await self._async_load_holidays()
  File "/config/custom_components/holidays/calendar.py", line 105, in _async_load_holidays
    self._language,
    ^^^^^^^^^^^^^^
AttributeError: 'Holidays' object has no attribute '_language'
```

**Comment by WhimsySpoon** [comment]
In addition, that error appears to fire every 10 seconds.

**Comment by WhimsySpoon** [comment]
Just tried to delete and re-add the helper. When entering a Friendly name and selecting a Country, pressing Submit on the first page of the config flow renders a "Unknown error occured" and adds the following to the log:

````
2023-11-06 12:45:55.332 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/schema_config_entry_flow.py", line 342, in _async_step
    result = await self._common_handler.async_step(step_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/schema_config_entry_flow.py", line 132, in async_step
    return await self._async_form_step(step_id, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/schema_config_entry_flow.py", line 179, in _async_form_step
    return await self._show_next_step_or_create_entry(form_step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/schema_config_entry_flow.py", line 211, in _show_next_step_or_create_entry
    next_step_id_or_end_flow = await form_step.next_step(self._options)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/holidays/config_flow.py", line 32, in choose_second_step
    languages = localised_countries[options.get(const.CONF_COUNTRY)]
                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'GB'
````

**Comment by andreasbrett** [comment]
Had to re-configure my current holidays integration. While in **step 1** there was a country defined, In **step 1,5** there was no language selected. Once that was done, errors disappeared in my logs.

![image](https://github.com/bruxy70/Holidays/assets/6610451/23a6de1b-6913-4d47-a999-df168fe7e14e)

![image](https://github.com/bruxy70/Holidays/assets/6610451/1fd0b3da-c83e-4b69-acee-de75b278b3f0)

**Comment by WhimsySpoon** [comment]
Unfortunately it's not possible to navigate past the first page without getting the error.

**Comment by andreasbrett** [comment]
I could set the language through the UI but the errors came back quickly. Seems like `_language` is missing at several places and never read from config:

https://github.com/bruxy70/Holidays/blob/33dd367e681d570dc7ca1c00ba4e021f1cedaab3/custom_components/holidays/calendar.py#L36

https://github.com/bruxy70/Holidays/blob/33dd367e681d570dc7ca1c00ba4e021f1cedaab3/custom_components/holidays/calendar.py#L67

**Comment by bruxy70** [comment]
Sorry for the troubles, the latest release (1.9.9) should fix it. I have tested that with a number fo combinations and it seems to work. Let me know. Thanks.

**Comment by vlad36N** [comment]
Hi, Updated to 1.9.9. Good. Thank you.
You can close it.
